### ISSUE TITLE
Project fails to compile with a NuGet error in Japanese

### ISSUE THREAD

**Issue by JHoule** [ShinraTech/CCDK#1]
According to both one_to_one.vcxproj and many_to_many.vcxproj, there is an expected file at '.nuget/NuGet.targets'.

Since that file doesn't exist, the following Visual Studio project clause yields an error:
```XML
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>このプロジェクトは、このコンピューターにはない NuGet パッケージを参照しています。これらをダウンロードするには、NuGet パッケージの復元を有効にしてください。詳細については、http://go.microsoft.com/fwlink/?LinkID=322105 を参照してください。不足しているファイルは {0} です。</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.props'))" />
    <Error Condition="!Exists('..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.targets'))" />
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>
```

Note that requirement isn't present in one_to_many.vcxproj.

Also note that having a Japanese error message might be suboptimal.

**Comment by JNavok** [comment]
Thank you. I personally appreciate the feedback.

From: Jocelyn Houle
Reply-To: ShinraTech/CCDK
Date: Wednesday, July 29, 2015 at 10:35 AM
To: ShinraTech/CCDK
Subject: [CCDK] Project fails to compile with a NuGet error in Japanese (#1)


According to both one_to_one.vcxproj and many_to_many.vcxproj, there is an expected file at '.nuget/NuGet.targets'.

Since that file doesn't exist, the following Visual Studio project clause yields an error:

  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>このプロジェクトは、このコンピューターにはない NuGet パッケージを参照しています。これらをダウンロードするには、NuGet パッケージの復元を有効にしてください。詳細については、http://go.microsoft.com/fwlink/?LinkID=322105 を参照してください。不足しているファイルは {0} です。</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.props'))" />
    <Error Condition="!Exists('..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\directxtk_desktop_2013.2015.2.25.1\build\native\directxtk_desktop_2013.targets'))" />
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>

Note that requirement isn't present in one_to_many.vcxproj.

Also note that having a Japanese error message might be suboptimal.

**Comment by kengonakajima** [comment]
Hi, Thank you for your hints!

I have removed the unecessary EnsureNuGetPackageBuildImports element and tested with clean install. Please check v0.2.1 : https://github.com/ShinraTech/CCDK/releases/tag/v0.2.1
It has some more improvements on one_to_many setup.

Thanks,

**Comment by JHoule** [comment]
Confirmed that this issue no longer exists with the latest code.
