### ISSUE TITLE
Target 'backend' fails to link due to missing 'Win32_Interop.lib'

### ISSUE THREAD

**Issue by JHoule** [ShinraTech/CCDK#3]
Trying to compile 'backend' fails with the following link error:
```
1>LINK : fatal error LNK1104: cannot open file 'Win32_Interop.lib'
```

From what I gathered, this is related to redis which, while present under the externals directory, doesn't seem to be compiled nor pre-compiled.

**Comment by kengonakajima** [comment]
Hi, please see Setup.en.md step 2, building Redis.
Simply start with redis/msvs/RedisServer.sln and build then you get all things from Redis including Win32_Interop.lib.

**Comment by JHoule** [comment]
Building RedisServer.sln solves the problem.

Would it be worth referencing README.en.md in the main README.md; currently, it seems only README.ja.md is.  Or maybe make README.md a full-fledged, standalone document by itself (GitHub is good at referencing Markdown files, but my text editor isn't as good when I open up the checked out files).

**Comment by kengonakajima** [comment]
Sorry missing link to docs/README.en.md. Added!
