### ISSUE TITLE
Overview.en.md broken image

### ISSUE THREAD

**Issue by apophis42** [ShinraTech/CCDK#5]
<code>The below illustration compares the Shinra core system (for production titles), the MCS, and a game running without the Shinra system.

\<img src="without_shinra.png" width=150></code>

The path should be images/without_shinra.png

**Comment by shinraSimon** [comment]
Fixed, thanks!

https://github.com/ShinraTech/CCDK/commit/d0e45f5568f723b5805e1db22ff1bcb70685b366
